### ISSUE TITLE
creating files revision

### ISSUE THREAD

**Issue by dpastoor** [eddelbuettel/crp#4]
Hi, in discussing the recent revision with @yonicd https://github.com/eddelbuettel/crp/commit/0c28586924a50c1ee545607192a4a10b3e165ebf we are trying to wrap our head's around the policy as to try and stay within these guidelines.

For packages such as reprex() - copying to clipboard, or usethis - scaffolding folder structure, what is the appropriate methodology of developing packages with similar scope. For example, packages that generate project structures or other initialization activities. These functions are also invoked at a system level through other programs shelling out via `R -e "pkg::create_proj()"` 

I appreciate there is likely some nuance to the policy, and want to be clear about whether there are options such as only checking during interactive sessions and clearly logging, and likewise, how best to convey such situations to the CRAN check folks as to not overburden them.

Thanks!

**Comment by eddelbuettel** [comment]
Howdy.  I cannot answer this.  This site is just implementing a "differ" for the CRAN Policy page / site.

Maybe ask on the r-package-devel list?

**Comment by dpastoor** [comment]
Thanks dirk - I will followup and might link any responses back to here for anyone that stumbles on this issue later.

**Comment by eddelbuettel** [comment]
Let me be more forceful then in case this unclear:  you and I have precisely the same standing with respect to CRAN Policy:  "read only".   We are both consumer.  

This site does not implement, condone, plan, value, judge, comment, analyse ... CRAN Policy.  It just tells us when changes happen.

So *all question* need to be asked in front of actual CRAN Maintainers, hence maybe r-pkg-devel.

Linking back is as relevant as a linking back to, say, Disneyworld.   It has no bearing on what CRAN does.

**Comment by yonicd** [comment]
do you have that link in Disney?

**Comment by dpastoor** [comment]
I understand - I mean in terms of, if there is a response with guidance on r-devel or some other location, I will post the results here, in case someone else stumbles upon this issue, in which they can immediately see the reference.

I understand you/I are not influencing CRAN policy here - but if there is information provided elsewhere, I will cross-reference here in case people land here from google or otherwise.

**Comment by eddelbuettel** [comment]
I will lock this.  Please do not open issues such as this here.  If you have issues _with the code_ by all means do.  This is a distraction.
